MDA Custom Plugins
Azure/Security-Copilot pull request #126
Opened 2024-10-03 09:12 UTC by alfonso-greenbrook

Two plugins that use the CloudAppEvents table to provide insights about user activity and files detected by ATP.

2024-10-24 09:25 UTC, KwachSean commented
@alfonso-greenbrook provide sample prompts to use with this Custom plugin showcasing the different skills

2024-10-29 09:56 UTC, KwachSean requested changes
@alfonso-greenbrook provide Sample prompts in the readme file on how to use the skills associated with the plugin

2024-11-14 22:32 UTC, alfonso-greenbrook commented
@KwachSean Have added example prompts to both readme.md and .yaml files.

2025-01-24 10:17 UTC, KwachSean approved these changes
Here are the summarized changes:

Added new plugin files for MDA Advanced Threat Protection (ATP) Detection:

MDA_Advanced_Threat_Protection_Detection.yaml: Contains definitions and KQL skills for querying MDA tables for ATP events.
readme.md: Provides instructions and descriptions for the MDA ATP Detection plugin.
Added new plugin files for MDA Cloud App Events:

MDA_Cloud_Apps_Events.yaml: Contains definitions and KQL skills for querying MDA CloudAppEvents tables for various cloud app activities.
Readme.md: Provides instructions and descriptions for the MDA Cloud App Events plugin.
Minor correction:

Fixed a typo in the DisplayName for the skill GetExchangeOnlineActivityForUser in MDA_Cloud_Apps_Events.yaml.
These changes add new functionality for SOC analysts to get insights and investigate events related to Advanced Threat Protection and cloud app activities using custom KQL plugins.

2025-01-24 18:30 UTC, markrafn-msft approved these changes

2025-02-27 10:32 UTC, merged